### ISSUE TITLE
not compatible with wordpress version 4.8.1

### ISSUE THREAD

**Issue by Zawadidone** [blackus3r/wp-keyword-monitor#36]
Can you update the plugin for wordpress version 4.8.1 please. Already thanks

**Comment by blackus3r** [comment]
Can you show me the error message please.

**Comment by Zawadidone** [comment]
It doesn't show the settings in the wordpress menu

**Comment by blackus3r** [comment]
I will check this.

**Comment by Zawadidone** [comment]
Thanks

**Comment by blackus3r** [comment]
![bildschirmfoto 2017-09-04 um 19 00 58](https://user-images.githubusercontent.com/5137402/30034742-b666c45a-91a3-11e7-9e63-16d9e1dfc809.png)


The plugin works fine under 4.8.1 

Maybe there is another plugin running on your system, which influences my plugin?

**Comment by Zawadidone** [comment]
Okay thanks sorry for the issue
